color:
  saturation: 0.9319149
  brandStrength: 0.9319149
  rhythmicContrast: 0.6723405
  brandColors:
    - '#160E0C'
    - '#1F304B'
    - '#FDFDFC'
    - '#E0CE9A'
    - '#5D5342'
  lightness: 0.9319149
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.3255319
typography_spectrum: 0.803615
name: Bluebutterfly Club
